// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnHSr3uYwD2OnTIdWKbCgWBNsiP1tznk4',
    appId: '1:159679742036:web:7bfa4205b36f2137b4adc1',
    messagingSenderId: '159679742036',
    projectId: 'yummy-eats-c9471',
    authDomain: 'yummy-eats-c9471.firebaseapp.com',
    storageBucket: 'yummy-eats-c9471.appspot.com',
    measurementId: 'G-GR43ZZ5BM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWgTUCh28xx4qGjRKDybfP7wA3GgRYZyM',
    appId: '1:159679742036:android:ea6993423963d488b4adc1',
    messagingSenderId: '159679742036',
    projectId: 'yummy-eats-c9471',
    storageBucket: 'yummy-eats-c9471.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_bXK32JuFaLYNnM2z5Drazfh2eHLG3ws',
    appId: '1:159679742036:ios:ecca0d5bd44bb9d4b4adc1',
    messagingSenderId: '159679742036',
    projectId: 'yummy-eats-c9471',
    storageBucket: 'yummy-eats-c9471.appspot.com',
    iosBundleId: 'com.example.yummyEats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_bXK32JuFaLYNnM2z5Drazfh2eHLG3ws',
    appId: '1:159679742036:ios:45d3a5a569b7e6e9b4adc1',
    messagingSenderId: '159679742036',
    projectId: 'yummy-eats-c9471',
    storageBucket: 'yummy-eats-c9471.appspot.com',
    iosBundleId: 'com.example.yummyEats.RunnerTests',
  );
}
